#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/repos/dotfilesHypr/"
STYLE="onedark"
RASI="$DIR/rofi/themes/$STYLE/launcher.rasi"

# Run
rofi \
    -show drun \
	-kb-cancel Ctrl-q \
	-theme ${RASI}
